id: IDD848810
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:11:26+00:00'
last_modified: '2022-06-08T07:21:40.766352+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137884
  title: ཁྲི་རྒན་འཇམ་དབྱངས་ཐུབ་བསྟན་རྒྱ་མཚོའི་གསུང་རྩོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2122':
      image_group_id: I2PD18585
      title: ''
      total_pages: 714
      order: 1
      base_file: 2122.txt
    '4181':
      image_group_id: I2PD18586
      title: ''
      total_pages: 786
      order: 2
      base_file: 4181.txt
    '7891':
      image_group_id: I2PD18587
      title: ''
      total_pages: 666
      order: 3
      base_file: 7891.txt
    A753:
      image_group_id: I2PD18588
      title: ''
      total_pages: 698
      order: 4
      base_file: A753.txt
    22CE:
      image_group_id: I2PD18589
      title: ''
      total_pages: 658
      order: 5
      base_file: 22CE.txt
    4AF6:
      image_group_id: I2PD18590
      title: ''
      total_pages: 614
      order: 6
      base_file: 4AF6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
